//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

expect fun cMain_platformDependentCMain(): String
fun cMain_platformIndependentCMain() = "common"

fun TestCMain() {
  cMain_platformIndependentCMain()
  cMain_platformDependentCMain()
}
