//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

expect fun cTests_platformDependentCTests(): String
fun cTests_platformIndependentCTests() = "common"

fun TestCTests() {
  cTests_platformIndependentCTests()
  cTests_platformDependentCTests()
  cMain_platformIndependentCMain()
  cMain_platformDependentCMain()
}
