//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

public class PJvmTestsJavaClass {
    public String doStuff() {
       return "pJvmTests";
    }
}