//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/regularDependensOnMultiplatform/dependencies.txt`
//

public class PJvmJavaClass {
    public String doStuff() {
       return "pJvm";
    }
}