//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

public class AJvmJavaClass {
    public String doStuff() {
       return "aJvm";
    }
}