//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/multiplatformDependsOnRegular/dependencies.txt`
//

public class RJavaClass {
    public String doStuff() {
       return "r";
    }
}